export type Product = {
  id: string;
  name: string;
  code: string;
  category: string; // category slug
  categoryName: string;
  occasion: string;
  price: string;
  colour: string;
  fabric: string;
  work: string;
  includes: string[];
  description: string;
  crop: string; // css object-position
};

const p = (
  id: string,
  name: string,
  code: string,
  category: string,
  categoryName: string,
  occasion: string,
  price: string,
  colour: string,
  fabric: string,
  work: string,
  includes: string[],
  description: string,
  crop: string,
): Product => ({
  id,
  name,
  code,
  category,
  categoryName,
  occasion,
  price,
  colour,
  fabric,
  work,
  includes,
  description,
  crop,
});

export const PRODUCTS: Product[] = [
  p(
    "bw-01",
    "Maroon Velvet Barat Lehenga",
    "ABS-BW-01",
    "barat",
    "Barat",
    "Barat",
    "Rs. 245,000",
    "Deep maroon & antique gold",
    "Silk velvet with raw-silk lining",
    "Hand zardozi, kora dabka, naqshi",
    ["Embroidered choli", "Kali-cut lehenga", "Net dupatta with worked border"],
    "A full-weight barat lehenga built for the entrance — dense antique-gold zardozi across the choli and hem, with a kali-cut skirt that holds its flare through the night.",
    "50% 20%",
  ),
  p(
    "bw-02",
    "Zardozi Pishwas with Trail",
    "ABS-BW-02",
    "barat",
    "Barat",
    "Barat",
    "Rs. 210,000",
    "Oxblood & old gold",
    "Jamawar and organza",
    "Zardozi panels, sequin scatter",
    ["Pishwas frock", "Inner slip", "Trailed dupatta"],
    "A long pishwas with a soft trail, worked in tonal gold across the bodice and flare. Cut to your measurements with two fittings before delivery.",
    "35% 30%",
  ),
  p(
    "nk-01",
    "Pearl Chiffon Nikah Maxi",
    "ABS-NK-01",
    "nikah",
    "Nikah",
    "Nikah",
    "Rs. 128,000",
    "Ivory & pearl",
    "Double-layer chiffon",
    "Pearl clusters, silver dabka, crystal",
    ["Maxi shirt", "Chiffon trouser", "Pearl-edged dupatta"],
    "Restraint over sparkle — tonal silver dabka and pearl clusters on soft ivory chiffon, finished with a hand-rolled pearl edge on the dupatta.",
    "50% 25%",
  ),
  p(
    "nk-02",
    "Ivory Angrakha Set",
    "ABS-NK-02",
    "nikah",
    "Nikah",
    "Nikah",
    "Rs. 96,000",
    "Off-white",
    "Organza over raw silk",
    "Tonal thread, mukaish",
    ["Angrakha shirt", "Straight pants", "Organza dupatta"],
    "A crossover angrakha in off-white organza with mukaish scatter — light to wear, photographs beautifully in daylight nikah settings.",
    "60% 30%",
  ),
  p(
    "nk-03",
    "Jet Velvet Nikah Shirt",
    "ABS-NK-03",
    "nikah",
    "Nikah",
    "Nikah",
    "Rs. 112,000",
    "Jet black & silver",
    "Cotton-back velvet",
    "Silver dabka and crystal",
    ["Velvet shirt", "Silk trouser", "Net dupatta"],
    "Black velvet with silver dabka worked along the neckline and cuffs — a quieter, modern take on nikah dressing.",
    "40% 40%",
  ),
  p(
    "mh-01",
    "Gota Patti Gharara",
    "ABS-MH-01",
    "mehndi",
    "Mehndi",
    "Mehndi",
    "Rs. 74,000",
    "Marigold & mehndi green",
    "Cotton net and jamawar",
    "Gota patti, mirror work",
    ["Short shirt", "Kali gharara", "Gota-edged dupatta"],
    "Marigold yellow with orange gota patti and mirror work, built on a traditional kali gharara so it swings properly on the dance floor.",
    "45% 35%",
  ),
  p(
    "mh-02",
    "Mirror Work Festive Kurta",
    "ABS-MH-02",
    "mehndi",
    "Mehndi",
    "Mehndi",
    "Rs. 42,000",
    "Green & orange",
    "Khaddi net",
    "Sheesha mirror, thread",
    ["Kurta", "Culotte trouser", "Printed dupatta"],
    "A light festive kurta set for mehndi guests — mirror and thread work with plenty of movement and no weight.",
    "55% 30%",
  ),
  p(
    "wl-01",
    "Champagne Trail Gown",
    "ABS-WL-01",
    "walima",
    "Walima",
    "Walima",
    "Rs. 165,000",
    "Champagne",
    "Tissue and net",
    "Tonal pearl scatter, thread",
    ["Structured gown", "Detachable trail", "Tissue dupatta"],
    "A structured walima gown in champagne tissue with a detachable trail and tonal pearl scatter across the bodice.",
    "50% 20%",
  ),
  p(
    "wl-02",
    "Blush Pearl Maxi",
    "ABS-WL-02",
    "walima",
    "Walima",
    "Walima",
    "Rs. 138,000",
    "Blush pink",
    "Chiffon over satin",
    "Pearl and crystal",
    ["Maxi", "Satin slip", "Chiffon dupatta"],
    "Soft blush chiffon with pearl-and-crystal work concentrated at the yoke, falling into a clean floor-length line.",
    "40% 30%",
  ),
  p(
    "pw-01",
    "Sequin Chiffon Shirt",
    "ABS-PW-01",
    "party-wear",
    "Party Wear",
    "Formal evening",
    "Rs. 38,000",
    "Midnight & pewter",
    "Chiffon",
    "Sequin and tilla",
    ["Shirt", "Raw-silk trouser", "Sequin dupatta"],
    "An all-over sequin chiffon shirt with a clean modern cut — for engagements, dinners and mehndi guest lists.",
    "50% 35%",
  ),
  p(
    "pw-02",
    "Emerald Kurta Set",
    "ABS-PW-02",
    "party-wear",
    "Party Wear",
    "Semi-formal",
    "Rs. 29,000",
    "Emerald",
    "Raw silk",
    "Tilla thread",
    ["Kurta", "Straight pants", "Organza dupatta"],
    "Emerald raw silk with tilla thread along the placket and hem — the easy semi-formal that works for most invitations.",
    "60% 35%",
  ),
  p(
    "sr-01",
    "Worked Pallu Chiffon Saree",
    "ABS-SR-01",
    "sarees",
    "Sarees",
    "Formal",
    "Rs. 68,000",
    "Deep teal",
    "Pure chiffon",
    "Zardozi pallu, scattered motifs",
    ["Six-yard saree", "Blouse stitched to size", "Petticoat"],
    "Pure chiffon with a heavily worked pallu and scattered motifs through the body. Blouse cut to your measurements; pre-draping available on request.",
    "45% 30%",
  ),
  p(
    "sr-02",
    "Jamawar Saree",
    "ABS-SR-02",
    "sarees",
    "Sarees",
    "Formal",
    "Rs. 82,000",
    "Wine & gold",
    "Jamawar",
    "Woven motifs, worked border",
    ["Saree", "Contrast blouse", "Petticoat"],
    "Woven jamawar with a gold worked border — structured drape that holds pleats without pinning every ten minutes.",
    "55% 25%",
  ),
  p(
    "sg-01",
    "Kali Gharara",
    "ABS-SG-01",
    "sharara-gharara",
    "Sharara & Gharara",
    "Festive",
    "Rs. 89,000",
    "Rose pink & gold",
    "Jamawar and net",
    "Farshi border, kora dabka",
    ["Short shirt", "Kali gharara", "Net dupatta"],
    "The old Lucknowi proportion — a short worked shirt over a many-kali gharara with a deep farshi border.",
    "50% 40%",
  ),
  p(
    "sg-02",
    "Farshi Sharara",
    "ABS-SG-02",
    "sharara-gharara",
    "Sharara & Gharara",
    "Festive",
    "Rs. 95,000",
    "Antique rose",
    "Raw silk and organza",
    "Worked border, sequin",
    ["Long shirt", "Wide sharara", "Organza dupatta"],
    "Wide sharara panels with a worked farshi border, paired with a longer shirt for a softer, taller line.",
    "40% 30%",
  ),
  p(
    "fm-01",
    "Layered Anarkali Frock",
    "ABS-FM-01",
    "frocks-maxis",
    "Frocks & Maxis",
    "Festive",
    "Rs. 72,000",
    "Warm sand & copper",
    "Net over cancan",
    "Hand-worked hem, thread",
    ["Anarkali frock", "Inner and cancan", "Net dupatta"],
    "Layered net over cancan support for real volume, with a hand-worked hem that carries the weight of the flare.",
    "50% 25%",
  ),
  p(
    "fm-02",
    "Floor-Length Maxi",
    "ABS-FM-02",
    "frocks-maxis",
    "Frocks & Maxis",
    "Formal",
    "Rs. 58,000",
    "Deep bronze",
    "Silk crepe",
    "Tonal thread, bead detail",
    ["Maxi", "Slip", "Chiffon dupatta"],
    "A clean floor-length maxi in silk crepe with tonal thread and bead detail — long lines, minimal fuss.",
    "55% 35%",
  ),
  p(
    "mo-01",
    "Made-to-Order Bridal Commission",
    "ABS-MO-01",
    "made-to-order",
    "Made to Order",
    "Any ceremony",
    "Price on consultation",
    "Your palette",
    "Fabric sourced with you",
    "Embroidery designed to your brief",
    ["Consultation", "Sketch & fabric", "Embroidery", "Fittings"],
    "Bring a reference, a fabric, or only an idea. We sketch, source, embroider and fit — with the timeline agreed upfront before any work begins.",
    "50% 30%",
  ),
];

export const PRODUCT_CATEGORIES = Array.from(
  new Map(PRODUCTS.map((x) => [x.category, x.categoryName])).entries(),
).map(([slug, name]) => ({ slug, name }));

export const searchProducts = (query: string, category: string) => {
  const q = query.trim().toLowerCase();
  return PRODUCTS.filter((x) => {
    if (category !== "all" && x.category !== category) return false;
    if (!q) return true;
    return [
      x.name,
      x.code,
      x.categoryName,
      x.occasion,
      x.colour,
      x.fabric,
      x.work,
      x.description,
      x.includes.join(" "),
    ]
      .join(" ")
      .toLowerCase()
      .includes(q);
  });
};
