/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaratRouteImport } from './routes/barat'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as FrocksMaxisRouteImport } from './routes/frocks-maxis'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as MadeToOrderRouteImport } from './routes/made-to-order'
import { Route as MehndiRouteImport } from './routes/mehndi'
import { Route as NikahRouteImport } from './routes/nikah'
import { Route as PartyWearRouteImport } from './routes/party-wear'
import { Route as SareesRouteImport } from './routes/sarees'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShararaGhararaRouteImport } from './routes/sharara-gharara'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as WalimaRouteImport } from './routes/walima'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaratRoute = BaratRouteImport.update({
  id: '/barat',
  path: '/barat',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const FrocksMaxisRoute = FrocksMaxisRouteImport.update({
  id: '/frocks-maxis',
  path: '/frocks-maxis',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const MadeToOrderRoute = MadeToOrderRouteImport.update({
  id: '/made-to-order',
  path: '/made-to-order',
  getParentRoute: () => rootRouteImport,
} as any)
const MehndiRoute = MehndiRouteImport.update({
  id: '/mehndi',
  path: '/mehndi',
  getParentRoute: () => rootRouteImport,
} as any)
const NikahRoute = NikahRouteImport.update({
  id: '/nikah',
  path: '/nikah',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyWearRoute = PartyWearRouteImport.update({
  id: '/party-wear',
  path: '/party-wear',
  getParentRoute: () => rootRouteImport,
} as any)
const SareesRoute = SareesRouteImport.update({
  id: '/sarees',
  path: '/sarees',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShararaGhararaRoute = ShararaGhararaRouteImport.update({
  id: '/sharara-gharara',
  path: '/sharara-gharara',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const WalimaRoute = WalimaRouteImport.update({
  id: '/walima',
  path: '/walima',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barat': typeof BaratRoute
  '/collections': typeof CollectionsRoute
  '/frocks-maxis': typeof FrocksMaxisRoute
  '/lookbook': typeof LookbookRoute
  '/made-to-order': typeof MadeToOrderRoute
  '/mehndi': typeof MehndiRoute
  '/nikah': typeof NikahRoute
  '/party-wear': typeof PartyWearRoute
  '/sarees': typeof SareesRoute
  '/services': typeof ServicesRoute
  '/sharara-gharara': typeof ShararaGhararaRoute
  '/visit': typeof VisitRoute
  '/walima': typeof WalimaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barat': typeof BaratRoute
  '/collections': typeof CollectionsRoute
  '/frocks-maxis': typeof FrocksMaxisRoute
  '/lookbook': typeof LookbookRoute
  '/made-to-order': typeof MadeToOrderRoute
  '/mehndi': typeof MehndiRoute
  '/nikah': typeof NikahRoute
  '/party-wear': typeof PartyWearRoute
  '/sarees': typeof SareesRoute
  '/services': typeof ServicesRoute
  '/sharara-gharara': typeof ShararaGhararaRoute
  '/visit': typeof VisitRoute
  '/walima': typeof WalimaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barat': typeof BaratRoute
  '/collections': typeof CollectionsRoute
  '/frocks-maxis': typeof FrocksMaxisRoute
  '/lookbook': typeof LookbookRoute
  '/made-to-order': typeof MadeToOrderRoute
  '/mehndi': typeof MehndiRoute
  '/nikah': typeof NikahRoute
  '/party-wear': typeof PartyWearRoute
  '/sarees': typeof SareesRoute
  '/services': typeof ServicesRoute
  '/sharara-gharara': typeof ShararaGhararaRoute
  '/visit': typeof VisitRoute
  '/walima': typeof WalimaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/barat'
    | '/collections'
    | '/frocks-maxis'
    | '/lookbook'
    | '/made-to-order'
    | '/mehndi'
    | '/nikah'
    | '/party-wear'
    | '/sarees'
    | '/services'
    | '/sharara-gharara'
    | '/visit'
    | '/walima'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/barat'
    | '/collections'
    | '/frocks-maxis'
    | '/lookbook'
    | '/made-to-order'
    | '/mehndi'
    | '/nikah'
    | '/party-wear'
    | '/sarees'
    | '/services'
    | '/sharara-gharara'
    | '/visit'
    | '/walima'
  id:
    | '__root__'
    | '/'
    | '/barat'
    | '/collections'
    | '/frocks-maxis'
    | '/lookbook'
    | '/made-to-order'
    | '/mehndi'
    | '/nikah'
    | '/party-wear'
    | '/sarees'
    | '/services'
    | '/sharara-gharara'
    | '/visit'
    | '/walima'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaratRoute: typeof BaratRoute
  CollectionsRoute: typeof CollectionsRoute
  FrocksMaxisRoute: typeof FrocksMaxisRoute
  LookbookRoute: typeof LookbookRoute
  MadeToOrderRoute: typeof MadeToOrderRoute
  MehndiRoute: typeof MehndiRoute
  NikahRoute: typeof NikahRoute
  PartyWearRoute: typeof PartyWearRoute
  SareesRoute: typeof SareesRoute
  ServicesRoute: typeof ServicesRoute
  ShararaGhararaRoute: typeof ShararaGhararaRoute
  VisitRoute: typeof VisitRoute
  WalimaRoute: typeof WalimaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barat': {
      id: '/barat'
      path: '/barat'
      fullPath: '/barat'
      preLoaderRoute: typeof BaratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frocks-maxis': {
      id: '/frocks-maxis'
      path: '/frocks-maxis'
      fullPath: '/frocks-maxis'
      preLoaderRoute: typeof FrocksMaxisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/made-to-order': {
      id: '/made-to-order'
      path: '/made-to-order'
      fullPath: '/made-to-order'
      preLoaderRoute: typeof MadeToOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mehndi': {
      id: '/mehndi'
      path: '/mehndi'
      fullPath: '/mehndi'
      preLoaderRoute: typeof MehndiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nikah': {
      id: '/nikah'
      path: '/nikah'
      fullPath: '/nikah'
      preLoaderRoute: typeof NikahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party-wear': {
      id: '/party-wear'
      path: '/party-wear'
      fullPath: '/party-wear'
      preLoaderRoute: typeof PartyWearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sarees': {
      id: '/sarees'
      path: '/sarees'
      fullPath: '/sarees'
      preLoaderRoute: typeof SareesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharara-gharara': {
      id: '/sharara-gharara'
      path: '/sharara-gharara'
      fullPath: '/sharara-gharara'
      preLoaderRoute: typeof ShararaGhararaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walima': {
      id: '/walima'
      path: '/walima'
      fullPath: '/walima'
      preLoaderRoute: typeof WalimaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaratRoute: BaratRoute,
  CollectionsRoute: CollectionsRoute,
  FrocksMaxisRoute: FrocksMaxisRoute,
  LookbookRoute: LookbookRoute,
  MadeToOrderRoute: MadeToOrderRoute,
  MehndiRoute: MehndiRoute,
  NikahRoute: NikahRoute,
  PartyWearRoute: PartyWearRoute,
  SareesRoute: SareesRoute,
  ServicesRoute: ServicesRoute,
  ShararaGhararaRoute: ShararaGhararaRoute,
  VisitRoute: VisitRoute,
  WalimaRoute: WalimaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
